INFO:tornado.access:200 GET /checkid/qpqp (192.168.43.1) 9.71ms
INFO:tornado.access:200 GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (192.168.43.1) 10.71ms
INFO:tornado.access:204 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%AB/email/cwh6272@naver.com (192.168.43.1) 4.80ms
INFO:tornado.access:204 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%AB/email/cwh6272@naver.com (192.168.43.1) 3.79ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:204 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%AB/email/cwh6272@naver.com (192.168.43.1) 6.57ms
INFO:tornado.access:204 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%AB/email/cwh6272@naver.com (192.168.43.1) 4.74ms
INFO:tornado.access:204 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%AB/email/cwh6272@naver.com (192.168.43.1) 4.50ms
INFO:tornado.access:204 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%AB/email/cwh6272@naver.com (192.168.43.1) 4.94ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Connection': 'Keep-Alive', 'User-Agent': 'okhttp/3.3.0', 'Host': '192.168.43.34:5000', 'Accept-Encoding': 'gzip'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 579, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 22.42ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Accept-Encoding': 'gzip', 'Host': '192.168.43.34:5000', 'User-Agent': 'okhttp/3.3.0', 'Connection': 'Keep-Alive'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 580, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 10.91ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Accept-Encoding': 'gzip', 'Host': '192.168.43.34:5000', 'User-Agent': 'okhttp/3.3.0', 'Connection': 'Keep-Alive'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 580, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 6.34ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 10.98ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 5.30ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 6.22ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 5.98ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 5.58ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 5.38ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 6.66ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 5.81ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 5.61ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 5.46ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (192.168.43.1) 8.83ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (192.168.43.1) 10.32ms
INFO:tornado.access:200 GET /finish_player/qpqp (192.168.43.1) 6.50ms
INFO:tornado.access:200 GET /start_player/qpqp (192.168.43.1) 5.33ms
INFO:tornado.access:200 GET /finish_player/qpqp (192.168.43.1) 6.05ms
INFO:tornado.access:200 GET /start_player/qpqp (192.168.43.1) 3.36ms
INFO:tornado.access:200 GET /finish_player/qpqp (192.168.43.1) 6.22ms
INFO:tornado.access:200 GET /rate/qpqp (192.168.43.1) 90.63ms
INFO:tornado.access:200 GET /ranking/qpqp (192.168.43.1) 13.86ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (192.168.43.1) 8.26ms
INFO:tornado.access:200 GET /finish_player/qpqp (192.168.43.1) 6.44ms
INFO:tornado.access:200 GET /start_player/qpqp (192.168.43.1) 4.49ms
INFO:tornado.access:200 GET /start_player/qpqp (192.168.43.1) 3.27ms
INFO:tornado.access:200 GET /finish_player/qpqp (192.168.43.1) 6.08ms
INFO:tornado.access:200 GET /finish_player/qpqp (192.168.43.1) 5.19ms
INFO:tornado.access:200 GET /rate/qpqp (192.168.43.1) 100.26ms
INFO:tornado.access:200 GET /ranking/qpqp (192.168.43.1) 26.11ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 6.62ms
ERROR:tornado.application:Uncaught exception GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1)
HTTPServerRequest(protocol='http', host='192.168.43.34:5000', method='GET', uri='/name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='192.168.43.1', headers={'Host': '192.168.43.34:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 581, in get
    SendMail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 21, in __init__
    self.send_confirm_mail(data)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 56, in send_confirm_mail
    title = self.get_email_content(lost)[0]
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py", line 24, in get_email_content
    f = open("app/import/find_"+lost+".txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/import/find_id.txt'
ERROR:tornado.access:500 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 6.52ms
INFO:tornado.access:200 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com (192.168.43.1) 5333.12ms
INFO:tornado.access:200 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/cwh6272@naver.com/id/qpqp (192.168.43.1) 5345.23ms
INFO:tornado.access:204 GET /checkid/qpqp (127.0.0.1) 6.23ms
INFO:tornado.access:204 GET /checkid/qpqp (127.0.0.1) 4.54ms
INFO:tornado.access:204 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/aaaa (127.0.0.1) 4.46ms
WARNING:tornado.access:404 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email/ (127.0.0.1) 22.11ms
WARNING:tornado.access:404 GET /name/%EC%B5%9C%EC%9A%B4%ED%95%99/email (127.0.0.1) 1.17ms
INFO:tornado.access:204 GET /checkid/qpqp (127.0.0.1) 5.46ms
INFO:tornado.access:200 GET /checkid/qpqpqp (127.0.0.1) 6.55ms
INFO:tornado.access:204 GET /checkid/qpqp (127.0.0.1) 3.74ms
INFO:tornado.access:204 GET /checkid/qpqp (127.0.0.1) 5.01ms
INFO:tornado.access:204 GET /checkid/qpqp (127.0.0.1) 3.74ms
INFO:tornado.access:204 GET /checkid/qpqp (127.0.0.1) 5.11ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/send_mail.py modified; restarting server
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:204 GET /players/qpqp/password/qpqp (172.30.1.1) 11.38ms
INFO:tornado.access:200 GET /checkid/qpqp (172.30.1.1) 4.83ms
WARNING:tornado.access:404 GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1) 13.34ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
ERROR:tornado.application:Uncaught exception GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1)
HTTPServerRequest(protocol='http', host='172.30.1.6:5000', method='GET', uri='/id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='172.30.1.1', headers={'Host': '172.30.1.6:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 534, in get
    update_player=Player(id=player_id, password=password, name=name, gender=gender, age=age, email=email, point=0)
TypeError: __init__() missing 1 required positional argument: 'nickname'
ERROR:tornado.access:500 GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1) 11.69ms
INFO:tornado.access:200 GET /checkid/qpqp (172.30.1.1) 7.59ms
ERROR:tornado.application:Uncaught exception GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1)
HTTPServerRequest(protocol='http', host='172.30.1.6:5000', method='GET', uri='/id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='172.30.1.1', headers={'Host': '172.30.1.6:5000', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.3.0'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 534, in get
    update_player=Player(id=player_id, password=password, name=name, gender=gender, age=age, email=email, point=0)
TypeError: __init__() missing 1 required positional argument: 'nickname'
ERROR:tornado.access:500 GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1) 2.31ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
ERROR:tornado.application:Uncaught exception GET /id/aaaaaa/pass/bbb/name/%EA%B8%B0%EB%AA%A8%EC%B0%8C/gender/%EB%82%A8/age/22/email/wnsgnl000@naver.com (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/id/aaaaaa/pass/bbb/name/%EA%B8%B0%EB%AA%A8%EC%B0%8C/gender/%EB%82%A8/age/22/email/wnsgnl000@naver.com', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4,ja;q=0.2', 'Host': 'localhost:5000', 'Accept-Encoding': 'gzip, deflate, br', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 534, in get
    update_player=Player(id=player_id, password=password, name=name, gender=gender, age=age, email=email, point=0)
TypeError: __init__() missing 1 required positional argument: 'nickname'
ERROR:tornado.access:500 GET /id/aaaaaa/pass/bbb/name/%EA%B8%B0%EB%AA%A8%EC%B0%8C/gender/%EB%82%A8/age/22/email/wnsgnl000@naver.com (127.0.0.1) 13.16ms
ERROR:tornado.application:Uncaught exception GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1)
HTTPServerRequest(protocol='http', host='172.30.1.6:5000', method='GET', uri='/id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='172.30.1.1', headers={'Host': '172.30.1.6:5000', 'Connection': 'Keep-Alive', 'User-Agent': 'okhttp/3.3.0', 'Accept-Encoding': 'gzip'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 534, in get
    update_player=Player(id=player_id, password=password, name=name, gender=gender, age=age, email=email, point=0)
TypeError: __init__() missing 1 required positional argument: 'nickname'
ERROR:tornado.access:500 GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1) 3.32ms
ERROR:tornado.application:Uncaught exception GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1)
HTTPServerRequest(protocol='http', host='172.30.1.6:5000', method='GET', uri='/id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com', version='HTTP/1.1', remote_ip='172.30.1.1', headers={'Host': '172.30.1.6:5000', 'Connection': 'Keep-Alive', 'User-Agent': 'okhttp/3.3.0', 'Accept-Encoding': 'gzip'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 534, in get
    update_player=Player(id=player_id, password=password, name=name, gender=gender, age=age, email=email, point=0)
TypeError: __init__() missing 1 required positional argument: 'nickname'
ERROR:tornado.access:500 GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1) 2.13ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:200 GET /id/aaaaaa/pass/bbb/name/%EA%B8%B0%EB%AA%A8%EC%B0%8C/gender/%EB%82%A8/age/22/email/wnsgnl000@naver.com (127.0.0.1) 14.08ms
INFO:tornado.access:200 GET /checkid/qpqp (172.30.1.1) 6.57ms
INFO:tornado.access:200 GET /id/qpqp/pass/qpqp/name/%EC%B5%9C%EC%9A%B4%ED%95%99/gender/%EB%82%A8/age/18/email/cwh6272@naver.com (172.30.1.1) 5.25ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 6.05ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 4.92ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.83ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 5.12ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.54ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 8.69ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 6.58ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 8.30ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 70.41ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 2.95ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 9.80ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 10.36ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.57ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.42ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.49ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.32ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.20ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 13.43ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.50ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.62ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.71ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.58ms
WARNING:tornado.access:404 GET /id/qpqp/password//name//email (172.30.1.1) 1.15ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 8.98ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 6.95ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 5.18ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 9.75ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.25ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.73ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.93ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 82.06ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 11.41ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 7.60ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 5.52ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.00ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.61ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.55ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.87ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.52ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 72.42ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 11.30ms
WARNING:tornado.access:404 GET /id/qpqp/password//nickname//email (172.30.1.1) 1.60ms
WARNING:tornado.access:404 GET /id/qpqp/password//nickname//email (172.30.1.1) 1.93ms
WARNING:tornado.access:404 GET /id/qpqp/password//nickname//email (172.30.1.1) 1.35ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 8.26ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 6.75ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.26ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.70ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.99ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.70ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.11ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 71.58ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 9.87ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 12.22ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.44ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.44ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.45ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.42ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.13ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 7.59ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 6.50ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.15ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 6.20ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.28ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.88ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 9.21ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 75.57ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 10.77ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 2.32ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 7.08ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.96ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.37ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 4.99ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.75ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 65.94ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 10.38ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 5.73ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.91ms
ERROR:tornado.application:Uncaught exception GET /editprofile/id/qpqp/password/qpqp/nickname/%22absb%22/email/wnsgnl000@naver.com') (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri="/editprofile/id/qpqp/password/qpqp/nickname/%22absb%22/email/wnsgnl000@naver.com')", version='HTTP/1.1', remote_ip='127.0.0.1', headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Connection': 'keep-alive', 'Host': 'localhost:5000', 'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4,ja;q=0.2', 'Accept-Encoding': 'gzip, deflate, br'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/common.py", line 58, in wrap
    profile = Profile(function_name=f.__qualname__, execution_sec=(time2-time1))
TypeError: __init__() missing 1 required positional argument: 'id'
ERROR:tornado.access:500 GET /editprofile/id/qpqp/password/qpqp/nickname/%22absb%22/email/wnsgnl000@naver.com') (127.0.0.1) 18.53ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.17ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.14ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.48ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.40ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:200 GET /editprofile/id/qpqp/password/qpqp/nickname/%22absb%22/email/wnsgnl000@naver.com') (127.0.0.1) 7.12ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 10.88ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.39ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 14.73ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 10.05ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 5.84ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.75ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.32ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.16ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.09ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.13ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 70.36ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 11.05ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 14.37ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 2.07ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.20ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 7.65ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 5.61ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.65ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.76ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.91ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 4.86ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 63.53ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 10.97ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.62ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password//nickname//email (172.30.1.1) 1.35ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 7.01ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 6.51ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.04ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 6.31ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.33ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.47ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.93ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 15.44ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 66.56ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password/qpqp/nickname/qpqp/emailcwh6272@naver (172.30.1.1) 12.84ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password/qpqp/nickname/qpqp/emailcwh6272@naver.com (172.30.1.1) 1.41ms
INFO:tornado.access:200 GET /editprofile/id/qpqp/password/qpqp/nickname/sss/email/wnsgnl000@naver.com') (127.0.0.1) 7.40ms
INFO:tornado.access:200 GET /editprofile/id/qpqp/password/qpqp/nickname/sss/email/wnsgnl000@naver.com') (127.0.0.1) 5.60ms
INFO:tornado.access:200 GET /editprofile/id/qpqp/password/qpqp/nickname/ssaa/email/wnsgnl000@naver.com') (127.0.0.1) 9.29ms
WARNING:tornado.access:404 GET /editprofile/id/qpqp/password/qpqp/nickname/qpqp/emailcwh6272@naver.com (172.30.1.1) 11.15ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 10.02ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 5.23ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.61ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.56ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.64ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.13ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.90ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 74.65ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 16.00ms
INFO:tornado.access:204 GET /editprofile/id/qpqp/password/qpqpqp/nickname/qpqp/email/cwh6272@naver.com (172.30.1.1) 4.99ms
INFO:tornado.access:200 GET /editprofile/id/qpqp/password/qpqp/nickname/qpqp/email/cwh6272@naver.com (172.30.1.1) 10.24ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/0 (172.30.1.1) 7.51ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.13ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 7.70ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 9.33ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 6.59ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 12.54ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 86.24ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.28ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 9.31ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 8.37ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.88ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.10ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.87ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 85.56ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 16.14ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 5.04ms
INFO:tornado.access:200 GET /id/qpqp/password/qpqpqp (172.30.1.1) 9.95ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:204 GET /players/qpqp/password/qpqp (172.30.1.1) 11.30ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqpqp (172.30.1.1) 7.04ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 6.06ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.83ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.89ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.35ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.37ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.49ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 67.12ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 11.11ms
INFO:tornado.access:204 GET /players/qpqp/password/qpqp (172.30.1.1) 8.82ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqpqp (172.30.1.1) 6.96ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 5.23ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.47ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
WARNING:tornado.access:404 GET /withdrawal/id/qpqp/password/ (172.30.1.1) 10.84ms
WARNING:tornado.access:404 GET /withdrawal/id/qpqp/password/ (172.30.1.1) 1.14ms
WARNING:tornado.access:404 GET /withdrawal/id/qpqp/password/ (172.30.1.1) 1.17ms
WARNING:tornado.access:404 GET /withdrawal/id/qpqp/password/ (172.30.1.1) 1.70ms
WARNING:tornado.access:404 GET /withdrawal/id/qpqp/password/ (172.30.1.1) 1.46ms
WARNING:tornado.access:404 GET /withdrawal/id/qpqp/password/ (172.30.1.1) 1.12ms
WARNING:tornado.access:404 GET /withdrawal/id/qpqp/password/ (172.30.1.1) 1.88ms
INFO:tornado.access:204 GET /players/qpqp/password/qpqp (172.30.1.1) 15.83ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqpqp (172.30.1.1) 7.17ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 8.83ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.64ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 5.50ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 9.60ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 5.69ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 16.59ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 86.90ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.50ms
INFO:tornado.access:204 GET /withdrawal/id/qpqp/password/qp (172.30.1.1) 6.72ms
INFO:tornado.access:200 GET /withdrawal/id/qpqp/password/qpqpqp (172.30.1.1) 5.44ms
INFO:tornado.access:200 GET /id/qpqp/password/qpqp (172.30.1.1) 9.59ms
INFO:tornado.access:204 GET /players/qpqp/password/qpqpqpqp (172.30.1.1) 7.99ms
INFO:tornado.access:204 GET /players/qpqp/password/qpqpqp (172.30.1.1) 6.61ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqp (172.30.1.1) 7.02ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 5.18ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.91ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.11ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.41ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.63ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.27ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 61.91ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 9.75ms
INFO:tornado.access:200 GET /withdrawal/id/qpqp/password/qpqp (172.30.1.1) 4.42ms
INFO:tornado.access:200 GET /id/qpqp/password/qpqpqpqp (172.30.1.1) 7.99ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 5.40ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.90ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.56ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.31ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.43ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.72ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 10.22ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 65.82ms
INFO:tornado.access:204 GET /players/qpqp/password/qpqp (172.30.1.1) 7.22ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqpqpqp (172.30.1.1) 7.64ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 6.74ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.16ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 3.60ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.62ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 4.80ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 15.36ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 64.27ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.33ms
INFO:tornado.access:200 GET /collect/qpqp/call_code/1 (127.0.0.1) 26.11ms
INFO:tornado.access:200 GET /quiznum/id/qpqp (127.0.0.1) 4.39ms
INFO:tornado.access:200 GET /collect/qpqp/call_code/2 (127.0.0.1) 17.99ms
INFO:tornado.access:200 GET /quiznum/id/qpqp (127.0.0.1) 3.98ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
ERROR:tornado.application:Uncaught exception GET /quiznum/id/qpqp (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/quiznum/id/qpqp', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate, br', 'Cache-Control': 'max-age=0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Host': 'localhost:5000', 'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4,ja;q=0.2'})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py", line 713, in get
    return int(pinvenlist)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
ERROR:tornado.access:500 GET /quiznum/id/qpqp (127.0.0.1) 18.29ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:200 GET /quiznum/id/qpqp (127.0.0.1) 5.25ms
INFO:tornado.access:204 GET /players/qpqp/password/qpqp (172.30.1.1) 10.71ms
INFO:tornado.access:204 GET /players/qpqp/password/qpqp (172.30.1.1) 7.17ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqpqpqp (172.30.1.1) 8.18ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 7.11ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 9.65ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 21.47ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.36ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 17.75ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 9.52ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 75.65ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 10.11ms
WARNING:tornado.access:404 GET /quiznum/id/qpqp/ (172.30.1.1) 16.05ms
INFO:tornado.general:/Users/HwiRiRic/Documents/seoulhang_server/seoulhang_server/app/apis.py modified; restarting server
INFO:tornado.access:200 GET /quiznum/id/qpqp (127.0.0.1) 6.16ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqpqpqp (172.30.1.1) 8.42ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 7.32ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 9.27ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 17.02ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 11.92ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 19.14ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 12.15ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 8.30ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 76.96ms
WARNING:tornado.access:404 GET /quiznum/id/qpqp/ (172.30.1.1) 12.99ms
WARNING:tornado.access:404 GET /quiznum/id/qpqp/ (172.30.1.1) 1.39ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqpqpqp (172.30.1.1) 6.03ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 6.18ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 10.33ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 18.27ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.13ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 21.12ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.56ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 75.77ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 12.55ms
INFO:tornado.access:200 GET /quiznum/id/qpqp (172.30.1.1) 4.07ms
INFO:tornado.access:200 GET /quiznum/id/qpqp (172.30.1.1) 3.91ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqpqpqp (172.30.1.1) 6.91ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 6.39ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.80ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 15.09ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.26ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 12.76ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 10.73ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 5.98ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 67.00ms
INFO:tornado.access:200 GET /quiznum/id/qpqp (172.30.1.1) 4.80ms
INFO:tornado.access:200 GET /players/qpqp/password/qpqpqpqp (172.30.1.1) 7.85ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 5.99ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 8.18ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 14.42ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 68.53ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 17.51ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.95ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 9.46ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 15.49ms
INFO:tornado.access:200 GET /quiznum/id/qpqp (172.30.1.1) 4.21ms
INFO:tornado.access:200 GET /collect/qpqp/call_code/1002 (172.30.1.1) 21.85ms
INFO:tornado.access:200 GET /check_player/qpqp (172.30.1.1) 8.25ms
INFO:tornado.access:200 GET /setting_language/qpqp/language/1 (172.30.1.1) 5.84ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 7.62ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 17.90ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.42ms
INFO:tornado.access:200 GET /start_player/qpqp (172.30.1.1) 22.89ms
INFO:tornado.access:200 GET /finish_player/qpqp (172.30.1.1) 6.92ms
INFO:tornado.access:200 GET /rate/qpqp (172.30.1.1) 86.96ms
INFO:tornado.access:200 GET /ranking/qpqp (172.30.1.1) 10.20ms
INFO:tornado.access:200 GET /quiznum/id/qpqp (172.30.1.1) 5.95ms
